#!/bin/sh
 
usage()
{
	echo "0. clean up ./Buildit clean"
	echo "1. build hisiv100 program ./Buildit hisiv100"		
}
 
if [ "$*" = "clean" ] ; then
    make -f nbproject/Makefile-hisiv100.mk QMAKE= SUBPROJECTS= .clean-conf
	make -f Makefile-exe clean
	make -f Makefile-armexe clean
elif [ "$*" = "hisiv100" ] ; then
    make -f nbproject/Makefile-hisiv100.mk QMAKE= SUBPROJECTS= .build-conf
elif [ "$*" = "android" ] ; then
    make -f nbproject/Makefile-Android.mk QMAKE= SUBPROJECTS= .build-conf
elif [ "$*" = "debug" ] ; then
    make -f Makefile-exe
elif [ "$*" = "armdebug" ] ; then
    make -f Makefile-armexe
else 
	usage;
fi
